---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guestbook-application # +operator-builder:field:name=namespace,type=string
spec:
  replicas: 3 # +operator-builder:field:name=guestBookReplicas,default=3,type=int
  selector:
    matchLabels:
      app.kubernetes.io/app: guestbook
      app.kubernetes.io/tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/app: guestbook
        app.kubernetes.io/tier: frontend
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v5 # +operator-builder:field:name=guestBookImage,type=string
          env:
            - name: GET_HOSTS_FROM
              value: dns
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80 # +operator-builder:field:name=guestBookContainerPort,default=80,type=int
