---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  labels:
    app.kubernetes.io/app: redis
    app.kubernetes.io/role: follower
    app.kubernetes.io/tier: backend
  namespace: guestbook-application # +operator-builder:field:name=namespace,type=string
spec:
  replicas: 2 # +operator-builder:field:name=redisFollowerReplicas,default=2,type=int
  selector:
    matchLabels:
      app.kubernetes.io/app: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/app: redis
        app.kubernetes.io/role: follower
        app.kubernetes.io/tier: backend
    spec:
      containers:
        - name: follower
          image: gcr.io/google_samples/gb-redis-follower:v2 # +operator-builder:field:name=redisFollowerImage,type=string
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379 # +operator-builder:field:name=redisFollowerContainerPort,default=6379,type=int
