---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app.kubernetes.io/app: redis
    app.kubernetes.io/role: follower
    app.kubernetes.io/tier: backend
  namespace: guestbook-application # +operator-builder:field:name=namespace,type=string
spec:
  ports:
    # the port that this service should serve on
    - port: 6379 # +operator-builder:field:name=redisFollowerServicePort,default=6379,type=int
      targetPort: 6379 # +operator-builder:field:name=redisFollowerContainerPort,default=6379,type=int
  selector:
    app.kubernetes.io/app: redis
    app.kubernetes.io/role: follower
    app.kubernetes.io/tier: backend
