# permissions for end users to edit guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook-editor-role
rules:
- apiGroups:
  - apps.demo.com
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.demo.com
  resources:
  - guestbooks/status
  verbs:
  - get
